receivers:
  otlp:
    protocols:
      grpc:

exporters:
 logging:
   loglevel: debug
 otlp:
   endpoint: https://otlp.nr-data.net:4317
   headers:
     api-key: "your-key"
   tls:
     insecure: false
     
processors:
  batch:

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]